[package]
name = "slow"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
rand = "0.8"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
byteorder = "1.5.0"

