[package]
name = "slow"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
rand = "0.8"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
mio = { version = "0.8.5", features = ["os-poll", "os-ext", "net"] }

